[build]
  command = "npm run build"
  publish = "dist/public"

[functions]
  directory = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index.cjs"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200